# 第四天

In [17]:
# 第一题
a = [1,2,3,4,5]
b = ','.join(map(str,a))
print(b)

1,2,3,4,5


In [43]:
# 第二题
a = [1,2,3,4,5]
b = int(input())
a.append(b)
for i in range(len(a) - 2, -1, -1):
    if a[i+1] < a[i]:
        a[i+1],a[i] = a[i],a[i+1]
print(a)

 3


[1, 2, 3, 3, 4, 5]


In [61]:
# 第三题
import numpy as np
X = np.array([[12,7,3],[4,5,6],[7,8,9]])
Y = np.array([[5,8,1],[6,7,3],[4,5,9]])
sum = np.zeros(X.shape)
for i in range(X.shape[0]):
    for j in range(X.shape[1]):
        sum[i][j] = X[i][j] + Y[i][j]
print(sum)
X + Y

[[17. 15.  4.]
 [10. 12.  9.]
 [11. 13. 18.]]


array([[17, 15,  4],
       [10, 12,  9],
       [11, 13, 18]])

In [67]:
# 第四题
a = [1,2,3,4,5]
m = int(input())
for _ in range(m):
    b = a.pop()
    a.insert(0,b)
a

 2


[4, 5, 1, 2, 3]

In [8]:
# 第五题
# Python中的变量有可变与不可变两种类型，请查找什么是可变（mutable）的、什么是不可变（immutable）的。并根据查到的资料，找到下⾯的代码为什么会报错
'''
dict = {
(1,1):0,
(2,2):1,
(3,3):2
}
dict = {
[1,1]:0,
[2,2]:1,
[3,3]:2
}

dict = {
{1,1}:0,
{2,2}:1,
{3,3}:2
}

print(dict ) 
print(dict ) 
print(dict )
'''
# 在Python中，变量的类型分为可变（mutable）和不可变（immutable）两种：
#不可变（immutable）类型：一旦创建，其值不能被改变。Python中的整数（int）、浮点数（float）、字符串（str）、元组（tuple）等都是不可变类型。对于不可变类型，如果你尝试改变它的值，实际上Python会创建一个新的对象，并将变量指向这个新对象。
#可变（mutable）类型：其值可以被改变。Python中的列表（list）、字典（dict）、集合（set）等都是可变类型。对于可变类型，你可以改变其内容而不需要创建新的对象。
# 字典使用的键需要不可变变量，在第一个字典中使用了元组是不可变的，第二个和第三个使用的是列表和集合都是可变的变量，不能作为字典的键

'\ndict = {\n(1,1):0,\n(2,2):1,\n(3,3):2\n}\ndict = {\n[1,1]:0,\n[2,2]:1,\n[3,3]:2\n}\n\ndict = {\n{1,1}:0,\n{2,2}:1,\n{3,3}:2\n}\n\nprint(dict ) \nprint(dict ) \nprint(dict )\n'

In [52]:
# 第六题
'''
if __name__ == "__main__":
    list = list(range(1000))
    for idx in range(len(list)):
        if list[idx] % 2 == 1:
            list.pop(idx)
    print(list)
'''
# 问题:当使用 list.pop(idx) 删除元素时，列表的大小会改变，这会影响到后续的索引值。
# 同时list作为变量名容易冲突
del list # 删除之前对于list的系列操作
if __name__ == "__main__":
    numbers = list(range(0,1000,1))  # 将 range 转换为列表
    for idx in range(len(numbers) - 1, -1, -1):  # 从末尾向前遍历
        if numbers[idx] % 2 == 1:  # 如果是奇数，删除该元素
            numbers.pop(idx)
    print(numbers)  # 输出没有奇数的列表

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310, 312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336, 338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 360, 362, 364, 366, 368, 370, 372, 374, 376, 378, 380, 382, 384, 386, 388, 390, 392, 394, 396, 398, 400, 402, 404, 406, 408, 410, 412, 414, 416, 418, 420,

In [83]:
# 第七题
class Ren:  # 节点类型
    def __init__(self, nol):
        self.no = nol  # 节点序号
        self.next = None


class Joseph:
    def __init__(self, n1, m1):
        self.n = n1
        self.m = m1
        self.first = Ren(1)  
        t = self.first
        for i in range(2, self.n + 1):
            p = Ren(i)
            t.next = p
            t = p
        t.next = self.first  

    def Jsequence(self):  # 求约瑟夫序列
        record = []
        for i in range(1, self.n + 1):
            p = self.first
            j = 1
            while j < self.m - 1:
                j += 1
                p = p.next
            q = p.next
            record = [record, q.no]
            p.next = q.next
            self.first = p.next
        print(record[-1])
        return record

if __name__ == "__main__":
    m = 3
    n = 233
    L = Joseph(n, m)
    print("n=%d,m=%d的约瑟夫序列的最后一个数字为:" % (n, m), end='')
    try:
        L.Jsequence()
    except:
        IndexError(print('no'))

n=233,m=3的约瑟夫序列的最后一个数字为:227
